// Mock data for demo purposes (when database is not available)

export const mockUsers = [
  {
    id: '1',
    email: 'john@example.com',
    name: 'John Doe',
    role: 'CUSTOMER',
  },
  {
    id: '2',
    email: 'jane@example.com',
    name: 'Jane Smith',
    role: 'OWNER',
  },
];

export const mockBoats = [
  {
    id: '1',
    name: 'Sea Breeze',
    description: 'Beautiful sailboat perfect for a day on the water',
    type: 'SAILBOAT',
    capacity: 6,
    pricePerDay: 250,
    location: 'Miami, FL',
    latitude: 25.7617,
    longitude: -80.1918,
    imageUrl: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
    ownerId: '2',
    available: true,
    owner: {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    averageRating: 4.8,
    reviewCount: 12,
    reviews: [],
  },
  {
    id: '2',
    name: 'Ocean Explorer',
    description: 'Luxury yacht with all amenities for an unforgettable experience',
    type: 'YACHT',
    capacity: 12,
    pricePerDay: 850,
    location: 'Fort Lauderdale, FL',
    latitude: 26.1224,
    longitude: -80.1373,
    imageUrl: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=800',
    ownerId: '2',
    available: true,
    owner: {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    averageRating: 5.0,
    reviewCount: 8,
    reviews: [],
  },
  {
    id: '3',
    name: 'Speedy Sam',
    description: 'Fast speedboat for thrill seekers and water sports',
    type: 'SPEEDBOAT',
    capacity: 4,
    pricePerDay: 180,
    location: 'Key West, FL',
    latitude: 24.5551,
    longitude: -81.7800,
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    ownerId: '2',
    available: true,
    owner: {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    averageRating: 4.5,
    reviewCount: 15,
    reviews: [],
  },
  {
    id: '4',
    name: 'Fishing Master',
    description: 'Well-equipped fishing boat for serious anglers',
    type: 'FISHING',
    capacity: 8,
    pricePerDay: 320,
    location: 'Naples, FL',
    latitude: 26.1420,
    longitude: -81.7948,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    ownerId: '2',
    available: true,
    owner: {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    averageRating: 4.7,
    reviewCount: 10,
    reviews: [],
  },
  {
    id: '5',
    name: 'Party Pontoon',
    description: 'Spacious pontoon boat perfect for group parties',
    type: 'PONTOON',
    capacity: 15,
    pricePerDay: 400,
    location: 'Tampa, FL',
    latitude: 27.9506,
    longitude: -82.4572,
    imageUrl: 'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800',
    ownerId: '2',
    available: true,
    owner: {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    averageRating: 4.9,
    reviewCount: 20,
    reviews: [],
  },
];

export const mockBookings = [
  {
    id: '1',
    boatId: '1',
    customerId: '1',
    startDate: '2024-12-01',
    endDate: '2024-12-03',
    totalPrice: 500,
    status: 'CONFIRMED',
    boat: mockBoats[0],
  },
];

export const mockReviews = [
  {
    id: '1',
    boatId: '1',
    userId: '1',
    rating: 5,
    comment: 'Amazing experience! The boat was in great condition.',
    createdAt: '2024-11-15',
    user: {
      id: '1',
      name: 'John Doe',
    },
  },
];
